export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const ADDED_CONVERSATIONS    = "ADDED_CONVERSATIONS";
export const ADDED_CONVERSATION     = "ADDED_CONVERSATION";

export const ADDED_NOTIFICATIONS    = "ADDED_NOTIFICATIONS";
export const ADDED_NOTIFICATION     = "ADDED_NOTIFICATION";

export const ADDED_MESSAGE     = "ADDED_MESSAGE";
export const EDITED_MESSAGE    = "EDITED_MESSAGE";
export const DELETED_MESSAGE   = "DELETED_MESSAGE";

export const ADDED_BOOKMARKS   = "ADDED_BOOKMARKS";
export const ADDED_BOOKMARK   = "ADDED_BOOKMARK";

export const IS_CONNECTIING  = "IS_CONNECTIING";